import { DbHouse } from "./houses.db-model";

export const HOUSES_MOCK: DbHouse[] = [
  {
    _id: "1",
    name: "Cozy Loft",
    property_type: "Apartment",
    room_type: "Entire home/apt",
    beds: 3,
    bedrooms: 2,
    bathrooms: 1,
    images: { picture_url: "https://picsum.photos/seed/house1/600/400" },
    address: { street: "Calle Mayor 123, Valencia", country: "Spain" },
    description: "Loft en el centro de la ciudad",
    reviews: [
      { reviewer_name: "Ana", comments: "Estancia genial", date: "2025-01-10T10:00:00.000Z" },
      { reviewer_name: "Luis", comments: "Muy limpio", date: "2025-01-05T12:00:00.000Z" }
    ],
  },
  {
    _id: "2",
    name: "Mountain Cabin",
    property_type: "House",
    room_type: "Entire home/apt",
    beds: 4,
    bedrooms: 3,
    bathrooms: 2,
    images: { picture_url: "https://picsum.photos/seed/house2/600/400" },
    address: { street: "Via Bosco 5, Trentino", country: "Italy" },
    description: "Cabaña con vistas increíbles",
    reviews: [],
  },
  {
    _id: "3",
    name: "Charming Flat",
    property_type: "Apartment",
    room_type: "Entire home/apt",
    beds: 1,
    bedrooms: 1,
    bathrooms: 1,
    images: { picture_url: "https://picsum.photos/seed/house3/600/400" },
    address: { street: "Rue Vieille du Temple 45, Paris", country: "France" },
    description: "Piso con encanto en el Marais",
    reviews: [{ reviewer_name: "Claire", comments: "Ubicación TOP", date: "2025-02-12T09:30:00.000Z" }],
  },
  {
    _id: "4",
    name: "Modern Studio",
    property_type: "Studio",
    room_type: "Entire home/apt",
    beds: 1,
    bedrooms: 1,
    bathrooms: 1,
    images: { picture_url: "https://picsum.photos/seed/house4/600/400" },
    address: { street: "Passeig de Gràcia 20, Barcelona", country: "Spain" },
    description: "Estudio moderno cerca de la playa",
    reviews: [],
  },
  {
    _id: "5",
    name: "Countryside House",
    property_type: "House",
    room_type: "Entire home/apt",
    beds: 5,
    bedrooms: 4,
    bathrooms: 2,
    images: { picture_url: "https://picsum.photos/seed/house5/600/400" },
    address: { street: "Strada del Vino 8, Toscana", country: "Italy" },
    description: "Casa rural rodeada de viñedos",
    reviews: [{ reviewer_name: "Marco", comments: "Tranquilidad absoluta", date: "2025-03-01T18:00:00.000Z" }],
  },
  {
    _id: "6",
    name: "City View Apartment",
    property_type: "Apartment",
    room_type: "Entire home/apt",
    beds: 2,
    bedrooms: 2,
    bathrooms: 2,
    images: { picture_url: "https://picsum.photos/seed/house6/600/400" },
    address: { street: "5th Ave 350, New York", country: "USA" },
    description: "Apartamento con vistas a Manhattan",
    reviews: [],
  },
  {
    _id: "7",
    name: "Traditional Ryokan",
    property_type: "Ryokan",
    room_type: "Private room",
    beds: 3,
    bedrooms: 2,
    bathrooms: 1,
    images: { picture_url: "https://picsum.photos/seed/house7/600/400" },
    address: { street: "Gion, Kyoto", country: "Japan" },
    description: "Ryokan tradicional con onsen",
    reviews: [{ reviewer_name: "Yuki", comments: "Experiencia auténtica", date: "2025-02-22T08:00:00.000Z" }],
  },
  {
    _id: "8",
    name: "Beach House",
    property_type: "House",
    room_type: "Entire home/apt",
    beds: 5,
    bedrooms: 3,
    bathrooms: 2,
    images: { picture_url: "https://picsum.photos/seed/house8/600/400" },
    address: { street: "Av. del Atlántico 12, Cádiz", country: "Spain" },
    description: "Casa a pie de playa",
    reviews: [],
  },
  {
    _id: "9",
    name: "Lake Cottage",
    property_type: "Cottage",
    room_type: "Entire home/apt",
    beds: 3,
    bedrooms: 2,
    bathrooms: 1,
    images: { picture_url: "https://picsum.photos/seed/house9/600/400" },
    address: { street: "Lakeview Rd 77, Michigan", country: "USA" },
    description: "Cabaña junto al lago",
    reviews: [{ reviewer_name: "John", comments: "Puesta de sol espectacular", date: "2025-01-20T19:45:00.000Z" }],
  },
  {
    _id: "10",
    name: "Alpine Chalet",
    property_type: "Chalet",
    room_type: "Entire home/apt",
    beds: 7,
    bedrooms: 5,
    bathrooms: 3,
    images: { picture_url: "https://picsum.photos/seed/house10/600/400" },
    address: { street: "Route des Pistes 9, Chamonix", country: "France" },
    description: "Chalet alpino para esquiadores",
    reviews: [],
  },
];
